esphome:
  name: esp32-3

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "5444f26f2d73646c25ac9dd2ae2a886c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-3 Fallback Hotspot"
    password: "NYqiq2fRgeb0"

captive_portal:

dallas:
  - pin: 23
sensor:
  - platform: dallas
    address: 0x0800000dde764928
    name: "Aquarium Temperature"