substitutions:
  friendly_name: "Projector controller"
  friendly_name_short: "Projector"


esphome:
  name: esp32-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "e4141d7a0a9a534fd8d8833b1bb4d986"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-1 Fallback Hotspot"
    password: "HDAhDTHNpHVv"

captive_portal:

uart:
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
    
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

switch: 
  - platform: template
    name: projector power
    id: projector_power
    turn_on_action:
      then:
        - switch.template.publish:
            id: projector_power
            state: ON
        - uart.write: "\r*pow=on#\r"
    turn_off_action:
      then:
        - switch.template.publish:
            id: projector_power
            state: OFF
        - uart.write: "\r*pow=off#\r"